name: Stealth Auto Clear Bot Runner

on:
  schedule:
    - cron: '0 */6 * * *' # සෑම පැය 6 කට වරක් Run වේ
  workflow_dispatch: # Manually Run කිරීමට

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Check for Session Data File
        id: check_session_file
        uses: andstor/file-existence-action@v1
        with:
          files: 'sessions/creds.json'

      - name: Load Session Data from Secret (if available)
        # මෙම පියවර ක්‍රියාත්මක වන්නේ creds.json නැති විට පමණක් වන අතර,
        # SESSION_DATA Secret එක හිස් නැති නම් පමණි.
        # Secrets කෙලින්ම 'if' වලට දැමීමෙන් වැළකී, එය environment variable එකකට දමයි.
        if: steps.check_session_file.outputs.files_exists == 'false'
        env:
          SESSION_DATA_SECRET: ${{ secrets.SESSION_DATA }} # Secret එක Environment Variable එකකට දමයි
        run: |
          if [ -n "$SESSION_DATA_SECRET" ]; then # Environment Variable එක හිස් නොවේ නම් පමණක්
            mkdir -p sessions
            echo "$SESSION_DATA_SECRET" > sessions/creds.json
            echo "Session data loaded from secrets."
          else
            echo "SESSION_DATA secret is empty or not set. Bot will try to generate QR code."
          fi

      - name: Start Bot and Wait for QR Code/Connection
        # Bot එක ආරම්භ කර QR Code/Connection සඳහා තත්පර 180ක් (මිනිත්තු 3ක්) රැඳී සිටියි
        run: |
          nohup node index.js > bot_output.log 2>&1 &
          timeout 180s tail -f bot_output.log || true

      - name: Save New Session Data to Output
        # Bot එක සාර්ථකව සම්බන්ධ වූ පසු, නව Session Data (creds.json) සොයා ගනී
        if: always() && steps.check_session_file.outputs.files_exists == 'false'
        run: |
          if [ -f sessions/creds.json ]; then
            SESSION_DATA_NEW=$(cat sessions/creds.json)
            echo "::notice file=sessions/creds.json::New session data generated. Please copy this JSON and set it as a repository secret named SESSION_DATA."
            echo "New Session JSON: $SESSION_DATA_NEW"
            echo "You need to update your 'SESSION_DATA' secret in repository settings if this is a new connection."
          else
            echo "::warning::creds.json not found after bot run. Connection might not have been established."
          fi
