name: Whatsapp Auto Clear Bot Runner

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Check for Session Data
        id: check_session
        uses: andstor/file-existence-action@v1
        with:
          files: 'baileys_auth_info/creds.json'

      - name: Get Session Data
        if: steps.check_session.outputs.files_exists == 'true'
        run: |
          mkdir -p baileys_auth_info # -p flag ensures parent directories are created
          echo "${{ secrets.SESSION_DATA }}" > baileys_auth_info/creds.json

      - name: Start Bot and Wait for Pair Code/Connection
        # Bot එක ආරම්භ කර තත්පර 60ක් නින්දට නොයා ඉන්න ඉඩ දෙයි
        # මෙහිදී nohup මඟින් Bot එක පසුබිමේ Run කරන අතර timeout මඟින් Runner එකට කාලය සීමා කරයි.
        run: |
          nohup node index.js > bot.log 2>&1 & # Bot එක background එකේ Run කර logs bot.log file එකට දමයි
          timeout 60s tail -f bot.log || true # තත්පර 60ක් bot.log file එක බලන් ඉන්නවා. timeout වුණොත් error එකක් නොදී continue වෙනවා.

      # Bot එක සම්බන්ධ වූ පසු හෝ Pair Code එක ලැබුණු පසු,
      # ඔබට Session Data (creds.json) Github Secret එකට Add කළ හැක.
      # මෙතැන් සිට Bot එක 24/7 ක්‍රියාත්මක වනු ඇත.
