name: Stealth Auto Clear Bot Runner

on:
  schedule:
    - cron: '0 */6 * * *' # සෑම පැය 6 කට වරක් Run වේ
  workflow_dispatch: # Manually Run කිරීමට

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Check for Session Data File
        id: check_session_file
        uses: andstor/file-existence-action@v1
        with:
          files: 'sessions/creds.json'
          
      - name: Load Session Data from Secret (if available)
        if: steps.check_session_file.outputs.files_exists == 'false'
        env:
          SESSION_DATA_SECRET: ${{ secrets.SESSION_DATA }} 
        run: |
          if [ -n "$SESSION_DATA_SECRET" ]; then 
            mkdir -p sessions
            echo "$SESSION_DATA_SECRET" > sessions/creds.json
            echo "Session data loaded from secrets."
          else
            echo "SESSION_DATA secret is empty or not set. Bot will try to generate Pair Code."
          fi
            
      - name: Start Bot and Get Pair Code (Direct Print)
        # Bot එක ආරම්භ කර Pair Code එක කෙලින්ම Console එකට print කරයි.
        # මෙම Step එක Bot එක ක්‍රියාත්මක වන තාක් කල් Block වී පවතී.
        timeout-minutes: 3 # මෙම Step එකට උපරිම මිනිත්තු 3ක් (තත්පර 180ක්) පමණක් ඉඩ දෙන්න
        run: |
          chmod +x start_bot.sh # Script එක execute කිරීමට අවසර දෙන්න
          ./start_bot.sh        # Script එක Run කරන්න. Pair Code එක Console එකටම print වේ.

      - name: Save New Session Data to Output
        # Bot එක සාර්ථකව සම්බන්ධ වූ පසු, නව Session Data (creds.json) සොයා ගනී
        if: always() && steps.check_session_file.outputs.files_exists == 'false'
        run: |
          if [ -f sessions/creds.json ]; then
            SESSION_DATA_NEW=$(cat sessions/creds.json)
            echo "::notice file=sessions/creds.json::New session data generated. Please copy this JSON and set it as a repository secret named SESSION_DATA."
            echo "New Session JSON: $SESSION_DATA_NEW"
            echo "You need to update your 'SESSION_DATA' secret in repository settings if this is a new connection."
          else
            echo "::warning::creds.json not found after bot run. Connection might not have been established."
          fi
